# Generated by Django 5.2.5 on 2025-08-28 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AlterField(
            model_name='userorganization',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('accountant', 'Accountant'), ('member', 'Member')], default='member', max_length=20),
        ),
        migrations.AddIndex(
            model_name='userorganization',
            index=models.Index(fields=['user', 'is_default'], name='user_organi_user_id_3c529b_idx'),
        ),
    ]
